// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOnmmoJdNaHFHjHHmSExCHg4zjnI7zJVE',
    appId: '1:148508225506:web:3a1dead17cf670192753bb',
    messagingSenderId: '148508225506',
    projectId: 'find-it-f5d35',
    authDomain: 'find-it-f5d35.firebaseapp.com',
    storageBucket: 'find-it-f5d35.firebasestorage.app',
    measurementId: 'G-MCHTC0WWZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu8Bbj-BBYwqHfCAEF-vM8zulklNH5ALY',
    appId: '1:148508225506:android:d554638ff27e161b2753bb',
    messagingSenderId: '148508225506',
    projectId: 'find-it-f5d35',
    storageBucket: 'find-it-f5d35.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCifKFR7BbsJdUyVvRaF6fO-T2sjeEcmS8',
    appId: '1:148508225506:ios:0962d30708775af72753bb',
    messagingSenderId: '148508225506',
    projectId: 'find-it-f5d35',
    storageBucket: 'find-it-f5d35.firebasestorage.app',
    iosClientId:
        '148508225506-7ip9p8l8v8lg8nrphvprlappj5okqmqd.apps.googleusercontent.com',
    iosBundleId: 'com.group22.findIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOnmmoJdNaHFHjHHmSExCHg4zjnI7zJVE',
    appId: '1:148508225506:web:25f3fc8765814fa92753bb',
    messagingSenderId: '148508225506',
    projectId: 'find-it-f5d35',
    authDomain: 'find-it-f5d35.firebaseapp.com',
    storageBucket: 'find-it-f5d35.firebasestorage.app',
    measurementId: 'G-DEXLDTC638',
  );
}
